add livescript support
slim-template/language-slim pull request #28
Opened 2017-11-16 04:02 UTC by Announcement

i'm too lazy to undo the readme stuff so you can deal with that.

2017-11-16 05:17 UTC, tshedor commented
Hey @Announcement I saw your note. Would you please remove the `package.json` and `README` edits? I'll merge after those are cleaned up.

2018-11-29 17:53 UTC, auvipy requested changes
If you don;t have time, to edit, you can allow edits from maintainers, so that we can edit them.

2018-11-29 17:53 UTC, auvipy commented on README.md
> -## Looking for maintainer(s)! See [this issue](https://github.com/slim-template/language-slim/issues/25).
undo readme edits please

2018-11-29 17:53 UTC, auvipy commented on package.json
> -  "repository": "https://github.com/slim-template/language-slim",
and this too.

2024-05-13 21:24 UTC, closed without merging